# Generated by Django 5.2.16 on 2026-08-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
