# Generated by Django 5.2.16 on 2026-08-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='unit_price',
            new_name='unit_cost_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('RETURN', 'Return'), ('RESTOCK', 'Restock')], max_length=10),
        ),
    ]
