# Generated by Django 5.2.16 on 2026-08-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_unit_price_transaction_unit_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('card', 'Card'), ('bank', 'Bank Transfer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('restock', 'Restock')], max_length=10),
        ),
    ]
